/**
 * Service to handle WebAuthn interactions for Biometric Verification.
 * This utilizes the Platform Authenticator (Windows Hello, TouchID, Android Biometrics)
 * to verify the user presence.
 */

export class BiometricService {
    /**
     * Checks if the platform supports WebAuthn and if a user-verifying platform authenticator is available.
     */
    static async isAvailable(): Promise<boolean> {
        if (!window.PublicKeyCredential) {
            return false;
        }

        try {
            // Check if a platform authenticator (like Windows Hello) is available
            const available = await window.PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();
            return available;
        } catch (e) {
            console.error("Error checking biometric availability:", e);
            return false;
        }
    }

    /**
     * Triggers the native OS biometric prompt (Windows Hello, etc.)
     * returns true if verification was successful.
     */
    static async verifyUser(): Promise<boolean> {
        if (!window.PublicKeyCredential) {
            throw new Error("Web Authentication API is not supported in this browser.");
        }

        // Challenge should effectively be generated by the server for security,
        // but for this client-side "Device Verification" proof-of-concept, we generate it here.
        const challenge = new Uint8Array(32);
        window.crypto.getRandomValues(challenge);

        const publicKey: PublicKeyCredentialRequestOptions = {
            challenge: challenge,
            timeout: 60000,
            rpId: window.location.hostname, // Must match the current domain
            userVerification: "required", // This forces the biometric prompt (Face/Fingerprint/PIN)
        };

        try {
            // We use navigator.credentials.create() with 'publicKey' to trigger an "authentication/registration" flow 
            // often used for checking user presence on the device. 
            // Ideally for pure auth, we use .get(), but .create() is often easier for "just verifying user is present" logic 
            // without needing pre-registered credentials on the server for this specific demo flow.
            // However, typically .get() is for authentication. Let's try .get() first as it's cleaner, 
            // but without a registered credential, .get() usually fails.
            //
            // TRICK: To verify "Owner of device" without a specific server account linked yet, 
            // we can try to Register a dummy credential (User Verification) which proves they passed the bio check.

            const userId = new Uint8Array(16);
            window.crypto.getRandomValues(userId);

            const credential = await navigator.credentials.create({
                publicKey: {
                    challenge: challenge,
                    rp: {
                        name: "PollSense Biometric Voting",
                        id: window.location.hostname
                    },
                    user: {
                        id: userId,
                        name: "voter@pollsense.com",
                        displayName: "PollSense Voter"
                    },
                    pubKeyCredParams: [{ alg: -7, type: "public-key" }],
                    authenticatorSelection: {
                        authenticatorAttachment: "platform", // Forces Platform Authenticator (Windows Hello)
                        userVerification: "required" // Forces Biometric/PIN
                    },
                    timeout: 60000,
                    attestation: "none"
                }
            });

            return !!credential;
        } catch (error: any) {
            console.error("Biometric verification failed:", error);
            // Handle "User cancelled" or "Not allowed" specifically if possible
            throw error;
        }
    }
}
